### ISSUE TITLE
Logout on back pressed.

### ISSUE THREAD

**Issue by Arpit98** [aditmodhvadia/Canteen_App#5]
**Modification in Feature**
On the Main Activity, pressing back button displays seek bar with the text "Press back once more to logout"

**Suggested Solution**
Pressing the back button should not log out user from the Application. It should exit the application or close the Navigation Drawer(If it is opened.)

**Alternative Solution**
Logout option can also be displayed in the option menu.

**Screenshot**
![whatsapp image 2018-11-17 at 11 23 54](https://user-images.githubusercontent.com/38467908/48659903-9ae0c200-ea7e-11e8-8afa-386cca2c51f4.jpeg)

**Comment by aditmodhvadia** [comment]
Thank you for the suggestion. It seems like a better design option and hence we will implement the same in the next release. There is a log out option in the navigation drawer hence we'll not add it in the options menu. We value your feedback and hope to get more of it.
