### ISSUE TITLE
Change color

### ISSUE THREAD

**Issue by avani247** [aditmodhvadia/Canteen_App#6]
Modification in feature:
On selecting quantities to add to the cart, the "No" and "Add to cart" options have a very light colour, it looks like they are disabled buttons.

Solution:
Change their color to Primary color of the theme.
![whatsapp image 2018-11-18 at 3 19 15 pm](https://user-images.githubusercontent.com/35555716/48670882-ac40d180-eb45-11e8-9fa6-71316bed7a61.jpeg)

**Comment by aditmodhvadia** [comment]
Change the textColor for them to the primary text color from colors.xml. Assigned to @avani247
